### ISSUE TITLE
domjudge/domserver:7.2.0 failed to startup

### ISSUE THREAD

**Issue by ChieloNewctle** [DOMjudge/domjudge-packaging#50]
## Description of the problem

The latest image domjudge/domserver:7.2.0 fails to run the `/script/start.sh` and logs:
```
[..] Updating database credentials file
sed: can't read webapp/app/config/parameters.yml: No such file or directory
```

## Your environment

- Ubuntu 18.04.3 LTS
- Docker 19.03.5, build 633a0ea838
- docker-compose 1.17.1
- domjudge/domserver:7.2.0

## Steps to reproduce

- Pull the docker image `mariadb:10.4` and `domjudge/domserver:7.2.0`.
- Run `docker-compose up -d` with `docker-compose.yml` and `domserver.env` in below.
- View the logs produced by the container of `domjudge/domserver:7.2.0`.

`docker-compose.yml`:
```yaml
version: "3"
services:
    database:
        image: mariadb:10.4
        hostname: database
        networks:
            - domjudge_net
        env_file:
            - domserver.env
        volumes:
            - ../data/database:/var/lib/mysql
        command: --max-connections=1000
    domserver:
        image: domjudge/domserver:7.2.0
        hostname: domserver
        networks:
            - domjudge_net
        env_file:
            - domserver.env
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        ports:
            - 127.0.0.1:5283:80
        depends_on:
            - database
networks:
    domjudge_net:
        driver: bridge
```

`domjudge.env`:
```
CONTAINER_TIMEZONE=Asia/Shanghai
TZ=Asia/Shanghai
MYSQL_HOST=database
MYSQL_DATABASE=domjudge
MYSQL_USER=domjudge
MYSQL_PASSWORD=b9NIhdxuJAhqcVW8bg4RgUni
MYSQL_ROOT_PASSWORD=UmHDaoOMl1Nzoke1lyV5FZbSfYXmJvkO
DJ_DB_INSTALL_BARE=1
```

## Expected behaviour

Success. Or it may fail due to some database or network problems.

## Actual behaviour

It fails during the early run of `/script/start.sh`.

Here is the full log:
```
[..] Setting timezone

Current default time zone: 'Asia/Shanghai'
Local time is now:      Tue Jan  7 13:11:05 CST 2020.
Universal Time is now:  Tue Jan  7 05:11:05 UTC 2020.

[ok] Container timezone set to: Asia/Shanghai

[..] Changing nginx and PHP configuration settings
[ok] Done changing nginx and PHP configuration settings

[..] Updating database credentials file
sed: can't read webapp/app/config/parameters.yml: No such file or directory
```

## Any other information that you want to share?

Image domjudge/domserver:7.1.2 works fine.
